### Variabili ambiente
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MTk5NjU5LCJpYXQiOjE3NTYxOTYwNTksImp0aSI6IjNmZGFmYzY2YTFkNTQzZjk5YzkyZDNkNTJjMmU0ODJkIiwidXNlcl9pZCI6MTE0fQ.IkQSCWTZURqgFff8z9c-JzSVcy7wSxt7jj4iEq4OaiE

### Recupero Forest Units
GET https://digimedfor.topview.it/api/get-forest-units/
Authorization: Bearer {{authToken}}
Accept: application/json

### Recupero prezzo ETH in EUR (Coingecko)
GET https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=eur
Accept: application/json