#Install REST Client for Visual Studio Code (Huachao Mao) from Extension 

POST https://digimedfor.topview.it/api/get-token/
Content-Type: application/json


{
    //"username": "Fabry@01", 
    //"password": "Giannone@2024"

    //"username": "mario_rossi", 
    //"password": "digimedfor"

    "username": "lorenzo", 
    "password": "puglet007"
}

#####

## Use access token value from get-token call
# {
#   "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzIzMzkwOSwiaWF0IjoxNzQ3MTQ3NTA5LCJqdGkiOiIxYjg0ZjYxNThlNjU0NzgwODhkMTM3NGUwZTY4OGU0NSIsInVzZXJfaWQiOjExMH0.53Vn7pvQz8qSzDvtSvAIYgwQJTGUzzMQxnGIyxnBLXo",
#   "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MTUxMTA5LCJpYXQiOjE3NDcxNDc1MDksImp0aSI6Ijc2NDQwNTI3NTg1ODQwN2VhYWUwZDg4ODQwMzUxNjNiIiwidXNlcl9pZCI6MTEwfQ.cW9NlKkvnDwlDBt5dgW4hw4Mu0RShi_rKiFCUgO4E6Q",
#   "username": "mario.rossi",
#   "email": "john.smith@gmail.com",
#   "fullName": "Mario Rossi",
#   "password": "pbkdf2_sha256$260000$U4awDktoNpV2XWzWHNpRjZ$wDBre1vZe0apnzFDZbyiYdXC8m9f/j+N1HGsKpT87u4=",
#   "roles": "Forest Owner",
#   "company": "",
#   "country": "Italy"
# }
@authAdmin = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNDQ4MjY3LCJpYXQiOjE3NTM0NDQ2NjcsImp0aSI6IjUzMGRjYzE5NzcyMTQzYTU5OTBmZWZkODJlZWZkNjFjIiwidXNlcl9pZCI6MTE0fQ.wPePSg35aUjHB8Fea0C4Q7A7ZlcbraeZAStPZUSjRgQ


GET https://digimedfor.topview.it/api/map/Lorenzo
Authorization: {{authAdmin}}